POST http://localhost:5000/api/user/registration HTTP/1.1
content-type: application/json

{
    "email": "tender67951Admin2121212@gmail.com",
    "password": "12345"
}

###
POST http://localhost:5000/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "tender67951Admin2121212@gmail.com",
    "password": "12345"
}

###

GET http://localhost:5000/api/user/auth?id=5 HTTP/1.1

###


