export const style = {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '25vw',
    height: '50vh',
    bgcolor: 'background.paper',
    borderRadius: 5,
    pt: 2,
    px: 4,
    pb: 3,
  }